### ISSUE TITLE
Component doesn't work anymore when using PHP serialization

### ISSUE THREAD

**Issue by alsar** [KonstantinCodes/messenger-kafka#20]
After adding support for the Symfony serializer https://github.com/KonstantinCodes/messenger-kafka/pull/6 the component stopped working when using the `PhpSerializer` which is the default serializer when using Messenger.

Because the `PhpSerializer` doesn't add `headers` (because it doesn't need to) but the `KafkaTransport` requires the key to be set [here](https://github.com/KonstantinCodes/messenger-kafka/blob/v0.9/Messenger/KafkaTransport.php#L148). 

Could we add a check if ` $payload['headers']` doesn't exist (or if `PhpSerializer` is used)? In this case just set it to null.

**Comment by KonstantinCodes** [comment]
Thank you @alsar 
I have pushed the change and added Tests.
