### ISSUE TITLE
Stable branch ready to be used ?

### ISSUE THREAD

**Issue by jbouzekri** [KonstantinCodes/messenger-kafka#5]
I see a stable branch with rdkafka 4.x support. Is it ready to be used in production ? Are you going to merge it in master ? If not, can you provide a todo list of all the things it needs to be done to merge it ?

**Comment by KonstantinCodes** [comment]
hi @jbouzekri 

Pretty much the only difference is that master continues to consume even after an exception has been thrown. This is not really what we want to happen with the kafka topics. So i made the stable branch.

Would you take a look at master to ensure it actually stops, when an exception is thrown?

**Comment by jbouzekri** [comment]
Okay. I am going to try the `master` branch with a 4.x librdakfa installed and focus on how the different error cases are handled. I will let you know once I have the result.

**Comment by nitso** [comment]
Hello. Do you have any news on this topic?

**Comment by KonstantinCodes** [comment]
@nitso Yeah, `master` now supports rdkafka 4

**Comment by nitso** [comment]
That's great news, thanks!
