### ISSUE TITLE
Feature request: Possibility to define partition

### ISSUE THREAD

**Issue by AlexOstrovsky** [KonstantinCodes/messenger-kafka#77]
Please add possibility to define concrete partions if we want to consume only some and not all partions of topic.
E.g. like this:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/8947035/220442735-32b3d7ad-3da8-4581-95bd-f9aab394d6a1.png">

@KonstantinCodes

**Comment by MaurizioMoreo** [comment]
@AlexOstrovsky did you ask this to reduce the setup time? I see that with 3 consumers (4 topics each) the partitions are assigned in about 1 minute. Any tips to reduce the setup time @KonstantinCodes ?
